// GENERATED by scripts/export-crisis-bundle.ts — do not edit by hand.
// Shape of apps/mobile/data/crisis/crisis-bundle.json (verified rows only).

export interface CrisisBundleCountry {
  iso2: string;
  name: string;
  emergencyNumber: string;
  emergencyNote: string | null;
  hasVerifiedHelplines: boolean;
}

export interface CrisisBundleHelpline {
  region: string;
  name: string;
  description: string;
  callNumber: string | null;
  textCapable: boolean;
  textNumber: string | null;
  displayOrder: number;
}

export interface CrisisBundle {
  generated: string;
  countries: CrisisBundleCountry[];
  helplines: CrisisBundleHelpline[];
}
